server:
  port: 8084
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - path=/users/**
            - id: HOTELSERVICE
              uri: lb://HOTELSERVICE
              predicates:
                - path=/hotels/**,/staffs/**  # whan  want all url use this ( /** )
            - id: RATINGSERVICE
              uri: lb://RATINGSERVICE
              predicates:
                - path=/ratings/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

